apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-kube-prometheus-alertmanager
  namespace: monitoring
labels:
  alertmanager.k8s.io/alertmanager: kube-prometheus
stringData:
  alertmanager.yaml: |
    global:
      resolve_timeout: 5m

    route:
      receiver: 'sns-notifications'
      group_wait: 10s
      group_interval: 30s
      repeat_interval: 1h

    receivers:
      - name: 'sns-notifications'
        sns_configs:
          - sigv4:
              region: us-east-1
            topic_arn: arn:aws:sns:us-east-1:723619976108:eks-alerts-topic

