apiVersion: v1
data:
  cwagentconfig.json: |-
    {
        "agent": {
          "region": "us-east-1"
        },
        "logs": {
          "metrics_collected": {
            "kubernetes": {
              "cluster_name": "flask-cluster",
              "metrics_collection_interval": 60
            }
          },
          "force_flush_interval": 5
        }
      }
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"cwagentconfig.json":"{\n    \"agent\": {\n      \"region\": \"us-east-1\"\n    },\n    \"logs\": {\n      \"metrics_collected\": {\n        \"kubernetes\": {\n          \"cluster_name\": \"flask-cluster\",\n          \"metrics_collection_interval\": 60\n        }\n      },\n      \"force_flush_interval\": 5\n    }\n  }"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"cwagentconfig","namespace":"amazon-cloudwatch"}}
  creationTimestamp: "2025-11-12T12:57:58Z"
  name: cwagentconfig
  namespace: amazon-cloudwatch
  resourceVersion: "552817"
  uid: 0498f0e4-f060-4f60-9dc6-2995049cc372
